#!/usr/bin/env bash
set -euo pipefail

# Generates VMs/Coolify/.env from shared VMs/.env so docker compose can auto-load it.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || true)
if [[ -z "$REPO_ROOT" ]]; then
  REPO_ROOT="$SCRIPT_DIR"
fi

VMS_ENV_FILE="$REPO_ROOT/VMs/.env"
LOCAL_ENV_FILE="$SCRIPT_DIR/.env"

if [[ ! -f "$VMS_ENV_FILE" ]]; then
  echo "ERROR: Missing $VMS_ENV_FILE. Run the Infisical fetch first." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$VMS_ENV_FILE"
set +a

if [[ -z "${COOLIFY_DB_DATABASE-}" ]]; then
  COOLIFY_DB_DATABASE="coolify"
fi

required_vars=(
  COOLIFY_DB_USERNAME
  COOLIFY_DB_PASSWORD
  COOLIFY_DB_DATABASE
  COOLIFY_REDIS_PASSWORD
  COOLIFY_PUSHER_APP_ID
  COOLIFY_PUSHER_APP_KEY
  COOLIFY_PUSHER_APP_SECRET
)

missing=false
for v in "${required_vars[@]}"; do
  if [[ -z "${!v-}" ]]; then
    echo "ERROR: $v is missing in $VMS_ENV_FILE" >&2
    missing=true
  fi
done
if [[ "$missing" == "true" ]]; then
  exit 1
fi

escape_env() {
  local val="$1"
  val="${val//\\/\\\\}"
  val="${val//\"/\\\"}"
  printf '%s' "$val"
}

{
  echo "# Generated by coolify_env_setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  for v in $(compgen -v | awk '/^COOLIFY_/'); do
    printf '%s="%s"\n' "$v" "$(escape_env "${!v}")"
  done
} > "$LOCAL_ENV_FILE"

echo "Wrote $LOCAL_ENV_FILE"
